// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgbhsvlztydsxetywjsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnYmhzdmx6dHlkc3hldHl3anNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjM1MzIsImV4cCI6MjA2NTI5OTUzMn0.k6IbT0cARqweGDEeDhxcy9Q1QDilkuAio_PKrzws5j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);